name: Build geoip.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup bgpq4
        run: |
          sudo apt-get update
          sudo apt-get install -y bgpq4

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
        shell: bash

      - name: Get DB-IP Lite Country MMDB database
        run: |
          curl -L -o dbip-country-lite.mmdb.gz "https://download.db-ip.com/free/dbip-country-lite-${{ env.YEAR }}-${{ env.MONTH }}.mmdb.gz"
          gzip -d dbip-country-lite.mmdb.gz
          mkdir -p db-ip
          mv dbip-country-lite*.mmdb ./db-ip/dbip-country-lite.mmdb

      - name: Get IPs from ASs
        run: |
          mkdir -p ./as
          touch ./as/banned_as.txt
          cloudflare=("AS13335")
          aws=("AS16509" "AS14618" "AS8987")
          fastly=("AS54113")
          cdn77=("AS60068" "AS212238")
          telegram=("AS62041" "AS211157")
          akamai=("AS20940" "AS16625" "AS12222" "AS33905" "AS63949")
          hetzner=("AS24940" "AS213230" "AS212317" "AS215859")
          digitalocean=("AS14061" "AS46652")
          ovh=("AS16276")
          for as in "${akamai[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/akamai.txt
          done
          for as in "${hetzner[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/hetzner.txt
          done
          for as in "${digitalocean[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/digitalocean.txt
          done
          for as in "${aws[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/aws.txt
          done
          for as in "${cdn77[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/cdn77.txt
          done
          for as in "${cloudflare[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/cloudflare.txt
          done
          for as in "${fastly[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/fastly.txt
          done
          for as in "${ovh[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/ovh.txt
          done
          for as in "${telegram[@]}"; do
              bgpq4 -F "%n/%l\n" $as >> ./as/telegram.txt
          done
          dest_file="./as/banned_as.txt"
          for file_path in ./as/*.txt; do
              if [ -f "$file_path" ] && [ "$file_path" != "$dest_file" ]; then
                  cat "$file_path" >> "$dest_file"
              fi
          done

      - name: Build GeoIP files
        run: |
          go run ./ -c ./config.json

      - name: Download Geosite
        run: |
          curl -sSL -o ./output/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat

      - name: Git push assets to "release" branch
        if: github.event_name != 'pull_request'
        run: |
          cd output || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add -A
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geofiles "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f geofiles release

      - name: Release and upload assets
        if: github.event_name != 'pull_request'
        run: |
          gh release create ${{ env.TAG_NAME }} -t ${{ env.RELEASE_NAME }} \
            ./output/geoip.dat \
            ./output/geosite.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
